version: "3.8"

services:
  helper-apis:
    build:
      dockerfile: Dockerfile
      context: .
    image: "helper-apis"
    restart: "always"
    ports:
      - "10000:8080"
    env_file: ./.env.docker
    stdin_open: true
